### ISSUE TITLE
Problème dans la configuration de la SV BOX

### ISSUE THREAD

**Issue by GuyliannEngels** [APouleur/aurore-pouleur-blog#2]
Salut @APouleur ,

Dans les commits , je peux voir que tu as mal encodé ton nom d'utilisateur et ton adresse mail dans la box de configuration de la sv box 2019. Peux tu vérifier et corriger cela au plus vite

**Comment by APouleur** [comment]
J'ai déjà corrigé l'adresse mail jeudi. Je ne vois aucune erreur ni dans le nom, ni dans l'adreesse mail.
[cid:0ae24e27-bb64-4f81-ac69-ee6e84b1d00b]
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : mardi 5 novembre 2019 09:57
À : APouleur/aurore-pouleur-blog <aurore-pouleur-blog@noreply.github.com>
Cc : Aurore POULEUR <Aurore.POULEUR@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : [APouleur/aurore-pouleur-blog] Problème dans la configuration de la SV BOX (#2)


Salut @APouleur<https://github.com/APouleur> ,

Dans les commits , je peux voir que tu as mal encodé ton nom d'utilisateur et ton adresse mail dans la box de configuration de la sv box 2019. Peux tu vérifier et corriger cela au plus vite

**Comment by GuyliannEngels** [comment]
ha ouais c'est possible ta derniere contribution sur ce dépot date d'il y a plus de 5 jours
